#!/bin/sh -e

if [ `uname` = 'Darwin' ]; then
    cat << EOM
Warning: Running $0 on Darwin may generate .dylib files instead of .so files.
EOM
    printf "Continue? (y/[n]) "
    read continue
    if [ 0$continue != 0y ]; then
	exit
    fi
fi

printf "This will anihilate PLIST.  Are you sure? (y/n) "
read resp
if [ 0$resp = 0'y' ]; then
    if [ `uname` = 'NetBSD' ]; then
	make='make'
    else
	make='bmake'
    fi
    ${make} distclean
    ${make} deinstall
    rm -f distinfo
    ${make} distinfo
    cat /dev/null > PLIST       # Send next install to temp area
    ${make} install
    ${make} print-PLIST > PLIST   # Send next install to real install tree
    ${make} clean
    ${make} deinstall
    ${make} install
fi

