#!/bin/sh -e

if [ `uname` = 'Darwin' ]; then
    cat << EOM
$0 should not be run on Darwin because it may generate
.dylib files instead of .so files.
EOM
    exit 1
fi

printf "This will anihilate PLIST.  Are you sure? (y/n) "
read resp
if [ 0$resp = 0'y' ]; then
    if [ `uname` = 'NetBSD' ]; then
	make='make'
    else
	make='bmake'
    fi
    ${make} distclean
    ${make} deinstall
    # ${make} distinfo
    ${make} makesum
    cat /dev/null > PLIST       # Send next install to temp area
    ${make} install
    ${make} print-PLIST > PLIST   # Send next install to real install tree
    ${make} clean
    ${make} deinstall
    ${make} install
fi

