#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-p pkgsrc-dir] 'pattern'\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
1)
    pkg_add=`which pkg_add`
    pkgsrc=`echo ${pkg_add%/sbin/pkg_add} | sed -e 's|pkg|pkgsrc|g'`
    pattern="$1"
    ;;

3)
    if [ $1 = '-p' ]; then
	pkgsrc=$2
	pattern="$3"
    else
	usage
    fi
    ;;

*)
    usage
    ;;
esac

ls -d "$pkgsrc"/*/*$pattern*
