#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-04-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-p prefix] [grep flags] [grep flags] regular-expression\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

prefix=/usr/pkgsrc
while [ 0`echo $1 | cut -c 1-1` = 0'-' ]; do
    if [ $1 = '-p' ]; then
	prefix=$2
	shift
	shift
    else
	grep_flags="$grep_flags $1"
	shift
    fi
done

# echo $prefix $grep_flags

case $# in
    1)
	filename='Makefile'
	re="$1"
	;;
    2)
	filename="$1"
	re="$2"
	;;
    *)
	usage
	;;
esac

set +e
cd $prefix
for category in *; do
    if [ -e $category/Makefile ]; then
	printf "Searching $category...\n"
	grep $grep_flags "$re" $category/*/$filename
    fi
done

