#!/bin/sh -e

if [ $# -gt 1 ]; then
    printf "Usage: $0 [dir]\n"
    exit 1
fi

if which bmake; then
    make=bmake
else
    make=make
fi

if [ $# = 1 ]; then
    pkg_add=`which pkg_add`
    pkgsrc=`echo ${pkg_add%/sbin/pkg_add} | sed -e 's|pkg|pkgsrc|g'`
    dir=`echo $pkgsrc/*/$1`
    count=`echo $dir | wc -w`
    if [ $count = 2 ]; then
	printf "Ambiguous: $dir\n"
	exit 1
    fi
    cd $dir
fi

printf "Remove distfile? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    $make distclean
else
    $make clean
fi
# Rebuild before deinstalling to minimize uninstalled time
$make
$make deinstall
$make install

