#!/bin/sh -e


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

if which bmake; then
    make=bmake
else
    make=make
fi

printf "Remove distfile? y/[n] "
read distclean
if [ 0$distclean = 0y ]; then
    $make distclean
else
    $make clean
fi
pkglint -e || true
pause
$make deinstall
$make install
