#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2015-09-16  Jasson BaconBegin
##########################################################################

usage()
{
    printf "Usage: $0 [category]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
0)
    category=`awk '$1 == "CATEGORIES=" { print $2 }' Makefile`
    if [ -z $category ]; then
	printf "No category found in Makefile.  Specify one using $0 category.\n"
	exit 1
    fi
    ;;
1)
    category=$1
    ;;
*)
    usage
esac

pkg=`basename $(pwd)`
diff -ruN --exclude CVS --exclude .svn ../../$category/$pkg .
