#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2021-06-11  ,,,         Begin
##########################################################################

usage()
{
    printf "Usage: $0 category/package\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
pkg=$1

cd $(pkgsrc-dir)/$pkg
pwd

cvs-status
pause

cvs -q diff -u 2>&1 | more
pause

pkg-check
pause

read -p 'Proceed with commit? y/[n] ' proceed
if [ 0"$proceed" = 0y ]; then
    cvs commit
    pause
    
    ctype=0
    while [ $ctype != 1 ] && [ $ctype != 2 ]; do
	cat << EOM

1.. Addition
2.. Update

EOM
	read -p 'Add (1) or update (2)? ' ctype
	case $ctype in
	1)
	    sbmake cce CTYPE=Added
	    cd ..
	    pkglint -F
	    cvs commit Makefile
	    ;;
	
	2)
	    sbmake cce CTYPE=Updated
	    ;;
	
	*)
	    printf "Please select 1 or 2.\n"
	    ;;
	
	esac
    done
fi
