#!/bin/sh -e

##########################################################################
#   Script description:
#       Generate a patch for a pkgsrc source file
#
#   Arguments:
#       Path to file from pkgsrc dir
#       
#   History:
#   Date        Name        Modification
#   2014-11-10  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 filename\n"
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    printf "Press return to continue..."
    read junk
}

##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

filename="$1"
if [ ! -e DESCR ]; then
    printf "$0 must be run from a package directory.\n"
    exit 1
fi

if [ ! -e "$filename.orig" ]; then
    printf "Error: No $filename.orig present.\n"
    exit 1
fi

pkg_dir=`pwd`
grandparent=${pkg_dir%/*/*}
package=${pkg_dir#$grandparent/}
WRKSRC=`auto-print-make-variable --base-dir $grandparent $package WRKSRC`
# Get relative path
WRKSRC=${WRKSRC#$pkg_dir/}

mkdir -p patches

# Go to WRKSRC and generate patch file
cd $WRKSRC
file1=${filename#./$WRKSRC/}
file=${file1#$WRKSRC/}
patch_file='patch-'`echo "$file" | sed -e 's|_|__|g' | sed -e 's|/|_|g'`
patch_path="$pkg_dir/patches/$patch_file"
# Broken
#if [ -e $patch_path ]; then
#    pkgdiff "$file.orig" "$file" | \
#        sed -n -e '/^---/,// p' > $patch_path.tail || true
#    sed -n -e '/\$NetBSD/,/^---/ p' $patch_path > $patch_path.head
#    cat $patch_path.head $patch_path.tail | uniq > $patch_path
#    rm -f $patch_path.head $patch_path.tail
#else
    pkgdiff "$file.orig" "$file" > $patch_path || true
#fi
: ${EDITOR:=vi}
cd $pkg_dir
$EDITOR $patch_path
make=$(pkgsrc-make)
$make makepatchsum
