#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-05-13  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 dir\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

dir=$1
if [ ! -d $dir ]; then
    printf "${dir}: No such directory.\n"
    exit 1
fi

case `uname` in
Linux)
    mount_cmd='mount --bind'
    ;;
NetBSD)
    mount_cmd=mount_null
    ;;
*)
    printf "`uname` is not yes supported.\n"
    exit 1
esac

rm -rf $dir/proc $dir/dev
mkdir -p $dir/proc $dir/dev
$mount_cmd /proc $dir/proc
$mount_cmd /dev $dir/dev
if [ `uname` = NetBSD ]; then
    rm -rf $dir/kern
    mkdir $dir/kern
    $mount_cmd /kern $dir/kern
fi
cp -fp /etc/resolv.conf $dir/etc

# Make sure umounts happen
set +e
chroot $dir /bin/sh

# Unmount in proper order
if [ `uname` = NetBSD ]; then
    umount $dir/kern
fi
umount $dir/dev
umount $dir/proc
