#!/bin/sh -e

if [ $# -gt 1 ]; then
    printf "Usage: $0 category/package\n"
    exit 1
fi

make=`pkgsrc-make`

if [ $# = 1 ]; then
    cd `pkgsrc-dir`/$1
fi

printf "Remove distfile? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    $make distclean
else
    $make clean
fi
# Rebuild before deinstalling to minimize uninstalled time
$make
$make deinstall
$make install
