#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 'pattern'\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
1)
    pkgsrc=`auto-pkgsrc-dir`
    pattern="$1"
    ;;

*)
    usage
    ;;
esac

ls -d "$pkgsrc"/*/*$pattern*
