#!/bin/sh -e

##########################################################################
#   Script description:
#       Search files in pkgsrc frameworks.
#
#   Note:
#       Keep in sync with port-grep!
#
#   Arguments:
#       -p pkgsrc-dir (default /usr/ports)
#       -f file (default Makefile)
#       -v (echo categories during search)
#
#   History:
#   Date        Name        Modification
#   2015-04-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-p pkgsrc-dir] [-f file] [-v] regular-expression [grep flags]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if which pkg_add; then
    pkg_add=`which pkg_add`
    pkgsrc=`echo ${pkg_add%/sbin/pkg_add} | sed -e 's|pkg|pkgsrc|g'`
else
    printf "Cannot determine pkgsrc pkgsrc-dir.\n"
    exit 1
fi

# Overwrite later if provided as an argument
filename='Makefile'

while [ 0`echo $1 | cut -c 1-1` = 0'-' ]; do
    case "$1" in
    -p)
	pkgsrc=$2
	shift
	shift
	;;
    -f)
	filename="$2"
	shift
	shift
	;;
    -v)
	verbose=1
	shift
	;;
    *)
	usage
	;;
    esac
done

if [ $# -lt 1 ]; then
    usage
fi

re="$1"
shift
grep_flags="$@"

set +e
cd $pkgsrc
for category in *; do
    if [ -e $category/Makefile ] && [ $category != Templates ]; then
	if [ 0$verbose = 01 ]; then
	    printf "Searching $category...\n"
	fi
	grep $grep_flags "$re" $category/*/$filename
    fi
done
