#!/bin/sh -e

if [ $# -gt 1 ]; then
    printf "Usage: $0 category/package\n"
    exit 1
fi

make=`pkgsrc-make`

if [ $# = 1 ]; then
    cd `auto-pkgsrc-dir`/$1
fi

printf "Remove distfile? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    $make distclean
else
    $make clean
fi
# Rebuild before deinstalling to minimize uninstalled time
$make
pkg_dir=`pwd | awk -F / '{ printf("%s/%s", $(NF-1), $NF); }'`
pkgbase=`auto-print-make-variable $pkg_dir PKGBASE`
pkg_delete -f $pkgbase
$make install
