#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-03  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 'partial-glob-pattern'\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ 0$1 = 0--exact ]; then
    exact=1
    shift
fi

case $# in
1)
    pkgsrc=`auto-pkgsrc-dir`
    pattern="$1"
    ;;

*)
    usage
    ;;
esac

if [ 0$exact = 01 ]; then
    ls -d "$pkgsrc"/*/$pattern
else
    ls -d "$pkgsrc"/*/*$pattern*
fi
